name: Release New Version
run-name: ${{ github.actor }} Releases New Version
on:
  push:
    branches:
      - master
env:
  HOST: "https://www.game-object.de/"
  PROJECT_ID: 13
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Zip dist folder
        run: |
          cd dist
          zip -r dist.zip ./*
          cd ..
      - name: Create Release
        run: |
          STATUS_CODE=$(curl -X POST --location "$HOST/api/v1/projects/$PROJECT_ID/releases" \
            -H "Authorization: Bearer $API_TOKEN_VAR" \
            -H "Accept: application/json" \
            -F "zip=@./dist/dist.zip;filename=dist.zip;type=application/zip" \
            --silent --output /dev/stderr --write-out "%{http_code}")
          if [ $STATUS_CODE -ne 200 ]; then exit 1; fi
        env:
          API_TOKEN_VAR: ${{ secrets.API_TOKEN }}
